### ISSUE TITLE
在一些老的手机上无法运行，比如我的三星i739。

### ISSUE THREAD

**Issue by jaffwu** [wysaid/Android-ffmpeg-CameraRecord#1]
javacv已经出了1.0版本，整个库改动很大，Android-ffmpeg-CameraRecord能不能更新到javacv-1.0？

**Comment by wysaid** [comment]
你自己更新一下呗， 这是我没事弄的小demo， 懒得弄了

**Comment by jaffwu** [comment]
不难，自己已更新。问题是，什么原因（效率。。。）让你不用javacv-1.0吗？

**Comment by wysaid** [comment]
嗯， 很大的一个原因 …… 懒……
我就喜欢你这样的勤快人， 来个 pull request我也更新一下呗， 么么哒
