### ISSUE TITLE
视频录制出来的是颠倒的？

### ISSUE THREAD

**Issue by zhenghx1105** [wysaid/Android-ffmpeg-CameraRecord#2]
根据demo运行出来的视频是颠倒的？如何解决？

**Comment by wysaid** [comment]
自己处理一下吧骚年， 这个只是个demo， 提供思路的。
屏幕坐标系与OpenGL坐标系不一样， 你可以设置 opengl里面 texture采样方向
也可以在shader里面改正， 再把view倒过来显示
这个写的不好， 懒得改了
