### ISSUE TITLE
怎么设置帧率呢？比如我每秒只有7帧，如何设置

### ISSUE THREAD

**Issue by LaoMengFlutter** [wysaid/Android-ffmpeg-CameraRecord#3]
比如我每隔70到100ms生成一帧，时间是变化的，我怎么设置能正常录制呢，现在demo录制出来播放的时候相当于快进。

**Comment by LaoMengFlutter** [comment]
so文件有支持64位手机的吗

**Comment by wysaid** [comment]
这个repo不怎么维护哈, 所有代码都在， so是 javacv提供的， 你可以在github上面搜索javacv获取源代码自己编译
