### ISSUE TITLE
请问下javacv是怎么编译出来的

### ISSUE THREAD

**Issue by iceAnson** [wysaid/Android-ffmpeg-CameraRecord#4]
现在最新的javacv已经移动到了github，但是我从github编译出的so库并没有ffmpegInvoke和neno的so库，你的库代码应该是googlecode的；
github的库编译之后出现录制过程中会出现闪退的情况，请问你的库是怎么编译出来的

**Comment by wysaid** [comment]
我使用的 javacv 预编译好的版本(jar+so), 并没有尝试直接使用源代码~
需要你自己处理一下
