### ISSUE TITLE
数组越界

### ISSUE THREAD

**Issue by huimingli** [wysaid/Android-ffmpeg-CameraRecord#5]
CameraDemoActivity中的FilterNames只有四种，FilterTypes有五种，所以在：
 for(int i = 0; i != FilterTypes.length; ++i) {
            MyButtons button = new MyButtons(this);
            button.filterType = FilterTypes[i];
            button.setText(FilterNames[i]);
            button.setOnClickListener(mFilterSwitchListener);
            layout.addView(button);
        }
中出现了越界

**Comment by wysaid** [comment]
谢谢提醒， 已修正 
[806efdc951fb9d6582185ac38500133318f6e50c](https://github.com/wysaid/Android-ffmpeg-CameraRecord/commit/806efdc951fb9d6582185ac38500133318f6e50c)
